# Generated by Django 5.1.7 on 2025-03-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
